# SPDX-FileCopyrightText: Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: MIT

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
        base: auto 
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 80%
        base: auto
        if_ci_failed: error
        threshold: 2%
ignore:
  - "cmd/"

comment:
  require_changes: true
