# SPDX-FileCopyrightText: Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "iocrypter"
SPDX-PackageSupplier = "Winni Neessen <wn@neessen.dev>"
SPDX-PackageDownloadLocation = "https://github.com/wneessen/iocrypter"

[[annotations]]
path = ["go.sum", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Winni Neessen <wn@neessen.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["flake.nix", "flake.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Winni Neessen <winni@neessen.dev>"
SPDX-License-Identifier = "MIT"
